name: taprush
description: TapRush - SlimNation arcade reflex game
publish_to: "none"

version: 0.1.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  image_picker: any
  shared_preferences: any
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
